Add new entitlement service
jfrog/xray-client-java pull request #43
Opened 2023-02-08 15:25 UTC by talarian1

2023-02-13 08:15 UTC, yahavi requested changes

2023-02-13 08:15 UTC, yahavi commented on src/main/java/com/jfrog/xray/client/impl/services/entitlements/EntitledImpl.java
> +    }
I couldn't find any usage for the constructors
```suggestion
```

2023-02-13 08:15 UTC, yahavi commented on src/main/java/com/jfrog/xray/client/impl/services/entitlements/EntitlementsImpl.java
> +            return null;
I think that hiding the exception is not a good idea. Can we remove this catch?

2023-02-19 11:50 UTC, talarian1 commented on src/main/java/com/jfrog/xray/client/impl/services/entitlements/EntitledImpl.java
> +    private final boolean isEntitled;
> Boolean variables should be prefixed with 'is'
This is the naming convention for boolean methods and variables used by Sun for the Java core packages. Using the is prefix solves a common problem of choosing bad boolean names like status or flag.

2023-02-19 14:19 UTC, yahavi approved these changes

2023-02-19 14:47 UTC, merged